version: '3.8'

services:
  gestore-soldini:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gestore-soldini
    ports:
      - "${APP_PORT:-5000}:5000"
    volumes:
      - .:/app
      - gestore-soldini-data:/app/db

volumes:
  gestore-soldini-data:
