version: '3.8'

services:
  gestore-soldini:
    image: python:3.12
    container_name: gestore-soldini
    working_dir: /app
    volumes:
      - .:/app
      - gestore-soldini-data:/app/db/database.db
    command: >
      sh -c "pip install -r requirements.txt &&
        flask run --host=0.0.0.0"
    ports:
      - "${APP_PORT}:5000"
  volumes:
    gestore-soldini-data